default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgresssss

development:
  <<: *default
  database: recipe_app_development
  host: localhost
  username: postgres
  password: 'Goodmorning123.'

test:
  <<: *default
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
  username: recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
